### ISSUE TITLE
The fookin bass is fookin raw

### ISSUE THREAD

**Issue by A1rPun** [Paradoxis/Gordon#2]
Great repo! I need this motivational speaker for my terminal :)
I'm not sure how you get these audio files but I want to request [`thefookinbassisfookinraw.mp3`](https://youtu.be/bCujO6Ujw_o)

**Comment by Paradoxis** [comment]
I'll add it (and a bunch more) this evening

**Comment by Paradoxis** [comment]
Wish: Granted
