### ISSUE TITLE
Add linux support

### ISSUE THREAD

**Issue by A1rPun** [Paradoxis/Gordon#3]
Hey Paradoxis,

I'm using your script already on linux but the syntax is a little different.
- `shuf -n 1`
- I'm using `mpv --really-quiet` to play the music files but maybe there is a more generic solution.
```
# Copyright (c) 2017 - Paradoxis
function gordon()
{
    if [[  $? != 0 ]]; then
        insult=$(ls $GORDON_INSULTS | shuf -n 1)
        mpv --really-quiet $GORDON_INSULTS/$insult &
        disown
    fi
}
GORDON_INSULTS=~/.insults
PROMPT_COMMAND=gordon
```

I've put this script in my `~/.bashrc` ;)

**Edit:** You can also use `ffplay`
```
ffplay v 0 -nodisp $GORDON_INSULTS/$insult & disown
```

**Comment by Paradoxis** [comment]
Implemented in 357a33d95a9bb665664c054c0c35d1735f0322e9
