### ISSUE TITLE
Check directory exists

### ISSUE THREAD

**Issue by A1rPun** [Paradoxis/Gordon#4]
Hey,

Because I have my `~/.bashrc` in multiple environments it is nice to check if the directory exists
Check if the directory exists with `&& -d $GORDON_INSULTS`

```
if [[ $? != 0 && -d $GORDON_INSULTS ]]; then
```

Otherwise you will get this:
```
bash: test: command not found
ls: cannot access '/home/git/Gordon/insults': No such file or directory
```

**Comment by Paradoxis** [comment]
@ me:

![1wsxjs](https://user-images.githubusercontent.com/6770124/31046143-e9fb54b6-a5f3-11e7-944d-739d711e21e1.jpg)

**Comment by A1rPun** [comment]
Lol great meme. But I guess this is a no 😛?

**Comment by Paradoxis** [comment]
@A1rPun bfae2390d42d7c59728e312ce4988f2c9238ea16 ;)

**Comment by A1rPun** [comment]
You are awesome! Thanks
