### ISSUE TITLE
New insults

### ISSUE THREAD

**Issue by A1rPun** [Paradoxis/Gordon#6]
I want to suggest the following insults:
```
cutthebullshitshallwe.mp3
tryalittlebitharder.mp3
whereisthelambsauce.mp3
youdeserveakickinthenuts.mp3
```
I have them in my current set-up and I can make a PR for adding these mp3's.

And a minor change: sftu30seconds.mp3 -> stfu30seconds.mp3

![ffd](https://user-images.githubusercontent.com/3754692/72552523-58d82980-3897-11ea-8e7c-5aa9c2602c12.jpg)

**Comment by Paradoxis** [comment]
Fookin delicious, throw the damn PR already
